version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ../build/Dockerfile
    volumes:
      - ../:/app
      # - go_mod:/go
    working_dir: /app
    ports:
      - 3050:3050
